# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83dc4281cc6ebbac6517242d2e88439c0bda3e09fe49404e779dd575cc6ebe6aeca062d6759f74f7d1bddce5a7bef8247f8aa8ad484f929424e3c6e44bacade8

test:
  secret_key_base: bed2a9af39371dc06ca83d29f1de146c84b36292e327b13764242fc93c28b049f127fecf3731d9f026fbc53e572516eb1b7e5fcf714907d3dc9dcd454eb07ea2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
